add allow_unreachable
this fixes a bug introduced in 104.1

2020-01-17 20:35:28 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Philips hue for hue
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 215, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/hue/__init__.py", line 114, in async_setup_entry
    allow_unreachable = config[CONF_ALLOW_UNREACHABLE]
KeyError: 'allow_unreachable'